# platform: Fedora 34 on x86_64 architecture
name: pyomo-tutorials
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - gurobi=9.1.2
  - pyomo=6.0.1
  - matplotlib=3.3.4
  - networkx=2.5.1
  - pyyaml=5.4.1
  - pandas=1.2.4
  - notebook=6.4.0
